apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: EduIt
        image: debianprueba1:latest
