pipeline{
    agent {label 'principal'}

    stages {
        stage('check'){
            steps{
                git 'https://github.com/DanteTocchetti/Deploy-dockerfile'
            }
        }
    }

    stage('Build'){
        steps{

            script{
                def imageName = "mi-imagen-docker"
                def imageTag = "latest"
                docker.build("${imageName}:${imageTag}", "-f Dockerfile .")
            }
        }
    }
}
